
export default new Map([
["src/content/blog/ce-emc-lvd-and-rohs-in-electronic-products-where-should-we-start-part-2-3-emc-tests.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fce-emc-lvd-and-rohs-in-electronic-products-where-should-we-start-part-2-3-emc-tests.mdx&astroContentModuleFlag=true")],
["src/content/blog/design-and-analysis-of-peak-detector-circuits.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdesign-and-analysis-of-peak-detector-circuits.mdx&astroContentModuleFlag=true")],
["src/content/blog/electromagnetic-shielding-design-tips.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Felectromagnetic-shielding-design-tips.mdx&astroContentModuleFlag=true")],
["src/content/blog/emc-design-cable-shield-chassis-and-reference-connections-where-and-how-should-they-be-connected.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Femc-design-cable-shield-chassis-and-reference-connections-where-and-how-should-they-be-connected.mdx&astroContentModuleFlag=true")],
["src/content/blog/mixed-signal-pcb-design-conflicts-between-emc-theory-and-reference-designs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmixed-signal-pcb-design-conflicts-between-emc-theory-and-reference-designs.mdx&astroContentModuleFlag=true")],
["src/content/blog/observing-distant-stars-from-angular-resolution-to-vlbi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fobserving-distant-stars-from-angular-resolution-to-vlbi.mdx&astroContentModuleFlag=true")],
["src/content/blog/optical-sensing-system-design-optical-elements-part-3-of-5.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptical-sensing-system-design-optical-elements-part-3-of-5.mdx&astroContentModuleFlag=true")],
["src/content/blog/optical-sensing-system-design-optical-elements-polarization-part-3-of-5.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptical-sensing-system-design-optical-elements-polarization-part-3-of-5.mdx&astroContentModuleFlag=true")],
["src/content/blog/optical-sensing-system-design-optical-elements-prism-part-3-of-5.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptical-sensing-system-design-optical-elements-prism-part-3-of-5.mdx&astroContentModuleFlag=true")],
["src/content/blog/optical-sensing-system-design-optical-elements-prism-retroreflectors-part-3-of-5.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptical-sensing-system-design-optical-elements-prism-retroreflectors-part-3-of-5.mdx&astroContentModuleFlag=true")],
["src/content/blog/optical-sensing-system-design-part-1-of-a-5-part-series.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptical-sensing-system-design-part-1-of-a-5-part-series.mdx&astroContentModuleFlag=true")],
["src/content/blog/optical-sensing-system-design-transmitter-and-receiver-selection-guide-2-5.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptical-sensing-system-design-transmitter-and-receiver-selection-guide-2-5.mdx&astroContentModuleFlag=true")],
["src/content/blog/power-mosfet-gate-drive-fundamentals-1-2.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpower-mosfet-gate-drive-fundamentals-1-2.mdx&astroContentModuleFlag=true")],
["src/content/blog/telescopes-that-learned-to-ignore-the-atmosphere.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftelescopes-that-learned-to-ignore-the-atmosphere.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-hidden-information-in-starlight.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-hidden-information-in-starlight.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-effect-of-slot-openings-in-a-faraday-cage-on-emc.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-effect-of-slot-openings-in-a-faraday-cage-on-emc.mdx&astroContentModuleFlag=true")],
["src/content/blog/welcome-to-free-zone.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwelcome-to-free-zone.mdx&astroContentModuleFlag=true")],
["src/content/blog/what-electric-eels-can-teach-us-about-emc-and-robotics.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhat-electric-eels-can-teach-us-about-emc-and-robotics.mdx&astroContentModuleFlag=true")],
["src/content/blog/where-to-start-with-ce-emc-lvd-and-rohs-in-electronic-products-part-3-3-lvd-test.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhere-to-start-with-ce-emc-lvd-and-rohs-in-electronic-products-part-3-3-lvd-test.mdx&astroContentModuleFlag=true")],
["src/content/blog/where-to-start-with-ce-emc-lvd-and-rohs-in-electronic-products.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhere-to-start-with-ce-emc-lvd-and-rohs-in-electronic-products.mdx&astroContentModuleFlag=true")]]);
		